export const arrLang = {
    "en-gb": {
      "lobby": "Back to Lobby",
      "shareHand": "Share Hand",
      "sitOut": "Sit Out",
      "leaveGame": "Leave Game",
      "reBuy": "Rebuy/Add-on",
      "addChips": "Add Chips",
      "tipTheDealer": "Tip the Dealer",
      "settings": "Settings",
      "multiTable": "Multi Table",
      "Cashier": "Cashier",
      "waitingnumber": "5",
      "joinWaitingList": "Join Waiting List",
      "Chat": "Chat",
      "logTab": "Log Tab",
      "foldToAnyBet": "FOLD TO ANY BET",
      "sitOutNextHand": "SIT OUT NEXT HAND",
      "waitForBB": "WAIT FOR BB",
      "autoMode": "Auto Mode",
      "autoFold": "Auto Fold",
      "showCards": "SHOW CARDS",
      "IMback": "I AM BACK",
      "user": "user",
      "user1": "user 1",
      "user2": "user 2",
      "user3": "user 3",
      "user4": "user 4",
      "user5": "user 5",
      "totalPot": "Total Pot",
      "totalWinPot": "Total Win Pot",
      "sidePot": "Side pot",
      "minutes": "Minutes",
      "seconds": "Seconds",
      "threeOfKind": "Three of a kind",
      "playerName": "Tangotag",
      "hudgeFundPanel": "Hudge Fund Panel",
      "freeBalance": "Free Balance",
      "totalPaid": "total paid",
      "street": "Street",
      "payOut": "Pay Out",
      "submit": "Submit",
      "winingHistory": "Wining history",
      "totalWins": "Total Wins",
      "hittingPair": "Hitting a Pair",
      "activitie": "Activitie:",
      "fold": "FOLD",
      "call": "CALL",
      "check": "CHECK",
      "check/Fold": "CHECK/FOLD",
      "raiseTo": "RAISE TO",
      "tip": "Tip:",
      "transferToTableWallet": "Transfer To Table Wallet",
      "yourGlobalBalance": "Your Global Balance",
      "min": "Min",
      "max": "Max",
      "transfer": "Transfer",
      "addtoTable": "Add To Table",
      "tableWallet": "Table Wallet",
      "tableBalance": "Table Balance",
      "autoReBuyChipsWhen": "Auto re-buy chips when",
      "chipsAreLowerThenBuyin": "Chips are lower then Buy-in",
      "runOutChips": "You run out of chips completely",
      "cancel": "CANCLE",
      "Cancel": "Cancel",
      "muteSounds": "Mute sounds",
      "autoMuckCards": "Auto muck cards",
      "ValueAsBBRatio": "Show values as BB ratio",
      "ValueAsUSD": "Show values as USD",
      "FourColours": "4 colors deck",
      "breakTime": "Break Time",
      "errorMessage": "Error Message",
      "errorBody": "One fine body…",
      "close": "Close",
      "shareHandMessage": "Link Copied",
      "thankYou": "Thank You",
      "GoToTable": "GO TO TABLE",
      "ReportMessage": "Thank you for your feedback.",
      "reportAction": "We will look into it shortly.",
      "allInsurance": "All In Insurance",
      "pay": "Pay",
      "save": "Save",
      "yes": "Yes",
      "nextTime": " Next Time",
      "finishedTournament": "Finished Tournament",
      "PlaceNum": "th place",
      "price": "Price:",
      "memberFrom": "Member From",
      "Report": "Report",
      "offensiveLang": "Offensive Language",
      "actLikeBot": "Act like a bot",
      "other": "Other",
      "describeReport": "Describe Your Report ",
    },
    "zh-tw": {
      "lobby": "Zurück zur Lobby",
      "shareHand": "Hand teilen",
      "sitOut": "Aussitzen",
      "leaveGame": "Spiel verlassen",
      "reBuy": "Nachkauf/Add-on",
      "addChips": "Chips hinzufügen",
      "tipTheDealer": "Geben Sie dem Händler ein Trinkgeld",
      "settings": "Einstellungen",
      "multiTable": "Multi-Tisch",
      "Cashier": "Kassiererin",
      "waitingnumber": "fünf",
      "joinWaitingList": "Treten Sie der Warteliste bei",
      "Chat": "Plaudern",
      "logTab": "Registerkarte „Protokoll“",
      "foldToAnyBet": "FOLDEN SIE AUF JEDEN EINSATZ“",
      "sitOutNextHand": "Setzen Sie die nächste Hand aus",
      "waitForBB": "Warte auf BB",
      "autoMode": "Automatikmodus",
      "autoFold": "Automatisch falten",
      "showCards": "ZEIGE KARTEN",
      "IMback": "ICH BIN ZURÜCK",
      "user": "Benutzer",
      "user1": "Benutzer 1",
      "user2": "Benutzer 2",
      "user3": "Benutzer 3",
      "user4": "Benutzer 4",
      "user5": "Benutzer 5",
      "totalPot": "Gesamttopf",
      "totalWinPot": "Gesamtgewinntopf",
      "sidePot": "Seitentopf",
      "minutes": "Protokoll",
      "seconds": "Sekunden",
      "threeOfKind": "Drei gleiche",
      "playerName": "Tangotag",
      "playerName": "Hugge Fund Panel",
      "freeBalance": "Kostenloses Guthaben",
      "totalPaid": "ganz bezahlt",
      "street": "Straße",
      "payOut": "auszahlen",
      "submit": "einreichen",
      "winingHistory": "Erfolgreiche Geschichte",
      "totalWins": "Gesamtsiege",
      "hittingPair": "Ein Paar treffen",
      "activitie": "Aktivitäten:",
      "fold": "FALTEN",
      "call": "ANRUF",
      "check": "ÜBERPRÜFEN",
      "check/Fold": "ÜBERPRÜFEN/FALTEN",
      "raiseTo": "ERHÖHEN, UM",
      "tip": "Tipp:",
      "transferToTableWallet": "Auf Tischgeldbörse übertragen",
      "yourGlobalBalance": "Ihr globales Gleichgewicht",
      "min": "Mindest",
      "max": "max",
      "transfer": "Überweisen",
      "addtoTable": "Zur Tabelle hinzufügen",
      "tableWallet": "Tischgeldbörse",
      "tableBalance": "Tischbilanz",
      "autoReBuyChipsWhen": "Chips automatisch neu kaufen, wenn",
      "chipsAreLowerThenBuyin": "Die Chips sind niedriger als das Buy-in",
      "runOutChips": "Ihnen gehen die Chips komplett aus",
      "cancel": "ABBRUCH",
      "Cancel": "Stornieren",
      "muteSounds": "Geräusche stumm schalten",
      "autoMuckCards": "Auto-Muck-Karten",
      "ValueAsBBRatio": "Werte als BB-Verhältnis anzeigen",
      "ValueAsUSD": "Werte als USD anzeigen",
      "FourColours": "4-Farben-Deck",
      "breakTime": "Pause",
      "errorMessage": "Fehlermeldung",
      "errorBody": "Ein schöner Körper…",
      "close": "Schließen",
      "shareHandMessage": "Link kopiert",
      "thankYou": "Danke",
      "GoToTable": "GEHE ZUM TISCH",
      "ReportMessage": "Danke für Ihre Rückmeldung.",
      "reportAction": "Wir werden uns das in Kürze ansehen.",
      "allInsurance": "Alles in der Versicherung",
      "pay": "zahlen",
      "save": "Speichern",
      "yes": "Ja",
      "nextTime": "Nächstes Mal",
      "finishedTournament": "Beendetes Turnier",
      "price": "Preis:",
      "PlaceNum": "Platz",
      "memberFrom": "Mitglied von",
      "Report": "Bericht",
      "offensiveLang": "Anstößige Sprache",
      "actLikeBot": "Benimm dich wie ein Bot",
      "other": "Andere",
      "describeReport": "Beschreiben Sie Ihren Bericht",
    }
  };
  let lang = "en-gb"; 

  $(document).ready(function() {
      setLanguage(lang);
  });
  
  function setLanguage(selectedLang) {
      lang = selectedLang;
      $(".lang").each(function(index, element) {
          $(this).text(arrLang[lang][$(this).attr("key")]);
      });
  }
  
  $(".translate").click(function() {
      var selectedLang = $(this).attr("id");
      setLanguage(selectedLang);
      getTranslation();
  });
  
  function getTranslation(key) {
    console.log(lang);
      return arrLang[lang][key];
  }
  
  export { getTranslation };
  