export const arrLang = {
    
    // "arbic": {
    //   "lobby": "العودة إلى الردهة",
    //   "shareHand": "مشاركة اليد",
    //   "sitOut": "الجلوس",
    //   "leaveGame": "",
    //   "reBuy": "أترك اللعبة",
    //   "addChips": "أضف رقائق",
    //   "tipTheDealer": "نصيحة التاجر",
    //   "settings": "إعدادات",
    //   "multiTable": "طاولة متعددة",
    //   "Cashier": "أمين الصندوق",
    //   "waitingnumber": "خمسة",
    //   "joinWaitingList": "الانضمام إلى قائمة الانتظار",
    //   "Chat": "محادثة",
    //   "logTab": "علامة تبويب السجل",
    //   "foldToAnyBet": "أضعاف إلى أي رهان",
    //   "sitOutNextHand": "اجلس في مكان قريب",
    //   "waitForBB": "انتظر بب",
    //   "autoMode": "نظام آلي",
    //   "autoFold": "الطي التلقائي",
    //   "showCards": "بطاقات العرض",
    //   "IMback": "أنا عدت مرة أخرى",
    //   "user": "مستخدم",
    //   "user1": "مستخدم 1",
    //   "user2": "مستخدم 2",
    //   "user3": "مستخدم 3",
    //   "user4": "مستخدم 4",
    //   "user5": "مستخدم 5",
    //   "totalPot": "مجموع وعاء",
    //   "totalWinPot": "مجموع الفوز وعاء",
    //   "sidePot": "وعاء جانبي",
    //   "minutes": "دقائق",
    //   "seconds": "ثواني",
    //   "threeOfKind": "ثلاثة من نوع",
    //   "playerName": "تانجوتاج",
    //   "hudgeFundPanel": "لوحة صندوق هودج",
    //   "freeBalance": "رصيد مجاني",
    //   "totalPaid": "مجموع المبالغ المدفوعة",
    //   "street": "شارع",
    //   "payOut": "سيصرف",
    //   "submit": "يُقدِّم",
    //   "winingHistory": "تاريخ الفوز",
    //   "totalWins": "إجمالي الانتصارات",
    //   "hittingPair": "ضرب زوج",
    //   "activitie": "أنشطة:",
    //   "fold": "يطوى",
    //   "call": "يتصل",
    //   "check": "يفحص",
    //   "check/Fold": "فحص/طي",
    //   "raiseTo": "يرفع ل",
    //   "tip": "نصيحة:",
    //   "transferToTableWallet": "نقل إلى محفظة الجدول",
    //   "yourGlobalBalance": "رصيدك العالمي",
    //   "min": "دقيقة",
    //   "max": "الأعلى",
    //   "transfer": "تحويل",
    //   "addtoTable": "أضف إلى الجدول",
    //   "tableWallet": "محفظة الطاولة",
    //   "tableBalance": "ميزان الجدول",
    //   "autoReBuyChipsWhen": "إعادة شراء الرقائق تلقائيًا متى",
    //   "chipsAreLowerThenBuyin": "الرقائق أقل من قيمة الشراء",
    //   "runOutChips": "نفاد رقائق البطاطس تماما",
    //   "cancel": "إلغاء",
    //   "Cancel": "يلغي",
    //   "muteSounds": "كتم الأصوات",
    //   "autoMuckCards": "بطاقات الوحل التلقائي",
    //   "ValueAsBBRatio": "",
    //   "ValueAsUSD": "Show values as USD",
    //   "FourColours": "4 colors deck",
    //   "breakTime": "Break Time",
    //   "errorMessage": "Error Message",
    //   "errorBody": "One fine body…",
    //   "close": "Close",
    //   "shareHandMessage": "Link Copied",
    //   "thankYou": "Thank You",
    //   "GoToTable": "GO TO TABLE",
    //   "ReportMessage": "Thank you for your feedback.",
    //   "reportAction": "We will look into it shortly.",
    //   "allInsurance": "All In Insurance",
    //   "pay": "Pay",
    //   "save": "Save",
    //   "yes": "Yes",
    //   "nextTime": " Next Time",
    //   "finishedTournament": "Finished Tournament",
    //   "PlaceNum": "th place",
    //   "price": "Price:",
    //   "memberFrom": "Member From",
    //   "Report": "Report",
    //   "offensiveLang": "Offensive Language",
    //   "actLikeBot": "Act like a bot",
    //   "other": "Other",
    //   "describeReport": "Describe Your Report ",
    // },
    
  };

  